name: test-notify
base: core20 
version: '0.1'
summary: Test snapcraft systemd watchdog oneshot
description: |
  A test.

grade: devel
confinement: strict

apps:
  no-notify:
    daemon: notify
    command: bin/daemon-no-notify
    plugs: [ daemon-notify ]

  notify:
    daemon: notify
    command: bin/daemon-notify-wrapper.sh
    plugs: [ daemon-notify,  network-control ]

parts:
  launchers:
    source: launchers
    plugin: dump
  daemon:
    source: .
    plugin: go
    build-packages: [ gcc ]
